# Generated by Django 4.0.3 on 2022-03-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('insured_name', models.CharField(max_length=250)),
                ('insured_job', models.CharField(max_length=100)),
                ('insured_address', models.CharField(max_length=500)),
                ('insured_city', models.CharField(max_length=100)),
                ('insured_state', models.CharField(max_length=100)),
                ('insured_zip', models.IntegerField()),
                ('insured_phone', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='creationId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.userdetails')),
            ],
        ),
    ]
