# Generated by Django 4.0.3 on 2022-03-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='insured_zip',
            field=models.IntegerField(null=True),
        ),
    ]
